name: mimir
description: "A multiplatform app for SIT students."

# The build version numbers is incremented automatically.
# DO NOT DIRECTLY CHANGE IT
version: 2.7.2+543

homepage: https://github.com/liplum/mimir
repository: https://github.com/liplum/mimir
issue_tracker: https://github.com/liplum/mimir/issues
documentation: https://github.com/liplum/mimir#readme

publish_to: none
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ^3.29.1

dependencies:
  flutter: { sdk: flutter }
  meta: ^1.12.0

  # I18n 11
  easy_localization: ^3.0.7+1
  intl: ^0.20.2

  # Basic
  logger: ^2.5.0
  device_info_plus: ^10.1.2
  path_provider: ^2.1.5
  version: ^3.0.2
  yaml: ^3.1.3
  path: ^1.8.3
  collection: ^1.18.0
  shared_preferences: ^2.5.2
  flutter_riverpod: ^2.6.1
  hive_ce: ^2.2.3
  hive_ce_flutter: ^1.1.0
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.0
  event_bus: ^2.0.1

  # String formatting
  format: ^1.5.2

  # Cryptography
  # Encryption (AES)
  encrypt: ^5.0.1
  # Hash (MD5)
  crypto: ^3.0.6
  uuid: ^4.5.1
  # Statistics
  statistics: ^1.1.3

  # HTML parser
  beautiful_soup_dart: ^0.3.0
  html: ^0.15.4

  # Dio (http client)
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.2.0

  # Android, iOS, macOS, web
  flutter_inappwebview: 6.1.5
  flutter_widget_from_html: ^0.15.2
  cookie_jar: ^4.0.8

  # Platform
  # Android / iOS / Windows Permission
  permission_handler: ^11.4.0
  # Open with other APP/programs
  open_file: ^3.5.10
  url_launcher: ^6.3.1
  file_picker: ^8.1.2
  share_plus: ^10.1.4
  app_settings: ^5.2.0

  # Get package info (version)
  package_info_plus: ^8.2.1

  # UI
  go_router: ^14.8.0
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  text_scroll: ^0.2.0
  markdown: ^7.3.0
  animations: ^2.0.11
  simple_icons: ^10.1.3
  sliver_tools: ^0.2.12
  flex_color_picker: ^3.7.0
  flutter_swipe_action_cell: ^3.1.5
  flutter_platform_widgets: ^7.0.1
  pull_down_button: ^0.10.2
  # read system theme color
  system_theme: ^3.1.2
  super_context_menu: ^0.8.24
  # Utils
  # dart.io.Platform API for Web
  universal_platform: ^1.1.0
  rettulf: ^3.0.0
  # lock
  async_locks: ^4.0.2
  # parse stacktrace
  sanitize_filename: ^1.0.5

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.9.0
  copy_with_extension_gen: ^6.0.0
  test: ^1.24.9
  msix: ^3.16.8

dependency_overrides:
  sqflite_android: 2.4.1

# ------------------------------------------------------------------------------

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/l10n/
