name: Flutter Build Android

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit to build'
        default: ""
        type: string

jobs:
  build_android:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v6
        with:
          repository: plum-tech/xiaoying-x
          ref: ${{ inputs.ref }}
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      # Configure Git with PAT for subsequent steps
      # This is the crucial step that sets up global credentials.
      - name: Configure Git for private dependencies
        run: |
          git config --global url."https://${{ secrets.MIMIR_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Configure Flutter CLI
        run: |
          flutter config --no-cli-animations

      - name: Flutter pub get
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_wait_seconds: 20
          shell: bash
          command: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi --no-pub

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.APK_SIGN_JKS_BASE64 }}
          keyStorePassword: ${{ secrets.APK_SIGN_JKS_PASSWORD }}
          keyPassword: ${{ secrets.APK_SIGN_ALIAS_PASS }}
          alias: ${{ secrets.APK_SIGN_ALIAS }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Android-release
          path: build/app/outputs/flutter-apk/*-signed.apk
